### ISSUE TITLE
细化、整理 Toggl 下 Project 的分类

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#103]
* [x] 把 Sleeping 作为 Basiclife 的一个 project 归并到生活成本中去
* [x] 细化 Basiclife 下的 project：
  * [x] Eating🍚
  * [x] Commuting🚌
  * [x] Cooking🔥
  * [x] Shower🛀&Washup🍼
  * [x] Morning Cleanup🚿
  * [x] Nap😴
* [x] 细化工作时间：
  * [x] GFI 团队。已经是过去式，我留恋 DART，这是真的
  * [x] 黑工团队。这是现在与项目相关的代码或沟通工作
  * [x] Regular-Meetings。包括站会、IPM 和 Retro
  * [x] Other-Meetings。其他会，或其他办公室非 workshop||session 的会议或活动 
  * [x] Workshops&Sessions。不区分 ThoughtWorks 的还是客户方的 W&S
* [x] 删除 meetings 的 tag
* [x] 归并并删除 Basiclife 大类
* [x] 归并并整理 Work 大类
* [x] 整理现有 Project 
  * [x] Tech-Programming 下的 Project？-> 没什么问题
  * [x] Reading-Methodology 这个 Client？-> 主要倾向书籍和资料的阅读吸取，倾向于方法论方面的书，so 人为加了 Methodology 这个 Client。目前看来也没什么问题
  * [x] 新增 Retrospective Client
  * [x] 目前觉得似乎没太大必要把睡眠和基本生活成本分开

就酱。看起来好多了。

![image](https://cloud.githubusercontent.com/assets/11895199/22129406/b4d38946-dee0-11e6-81d9-fed68144c7e5.png)

![image](https://cloud.githubusercontent.com/assets/11895199/22129419/ca5de9b4-dee0-11e6-9117-20bf08b6645e.png)

![image](https://cloud.githubusercontent.com/assets/11895199/22129424/d3e328b4-dee0-11e6-90f6-77f2ec3ee212.png)

![image](https://cloud.githubusercontent.com/assets/11895199/22129451/07712c26-dee1-11e6-91d7-7dd254c7ef35.png)

**Comment by JimmyLv** [comment]
emoji get✔️

**Comment by linesh-simplicity** [comment]
哈哈哈哈哈，必须有啊。

**Comment by JimmyLv** [comment]
这些 Basiclife 下面的 projects 会有什么 Description ？：
 Eating🍚
 Commuting🚌
 Cooking🔥
 Shower🛀&Washup🍼
 Morning Cleanup🚿
 Nap😴

**Comment by linesh-simplicity** [comment]
啊咧，没什么特别的 description。就是描述一下。

最近有点执迷计时，冷静一下。
