### ISSUE TITLE
2017 Capability 第一辑：AR&VR

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#105]
> 前言：在筛选新年的 capability 能力建设，最近终于渐渐意识到，IT 行业连同生活本身都是一直在变化的，特别是在这个科技发达的时代。我虽总觉得弊大于利，但毕竟也有利。跟上变化，也是生活的一部分常态，学着接纳并融入。

先说说 AR&VR。一直以来对新技术都是非常保守并且不太接纳的状态，我觉得技术本身就使人的交际方式与生活方式发生着变化，而 AR&VR 作为趋势似乎必然要介入并改变人的生活方式。这应该是规律，是无法避免的。没有过多深入行业本身，不过感觉上，**真实与假**在这个技术背景下变得更加难以识别了。这是我所无法逆转也无法忍受的。想象有一天，视觉听觉可以被模拟，感情感觉可以被模拟，你认为的观点感觉，别人看来不过是一场戏。作为计算速度上被计算机碾压的人类，真想不出这个种群最后还有什么继续存在的理由——如果没有了自由意志，没有了能力反抗——我似乎是在否定**人**的意义。我认为，“人”所自以为的特别、骄傲、意义，都是幻觉。

怎么这么像西部世界。感觉技术的发展始终要超过人类这个种群所能控制的极限。自求多福吧。

* Magic Leap
* Hololens
* Oculus
* https://www.zhihu.com/question/20191042
* https://www.zhihu.com/question/27717179/answer/37829755

**Comment by JimmyLv** [comment]
你这是要全栈啊

**Comment by linesh-simplicity** [comment]
这是不可能的哈哈哈，只是考察一下嘛
