### ISSUE TITLE
Ticktick retrospective I: Reorganise folders and implement best practices in book *Getting Things Done*

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#117]
* [x] 找静静要一下他的 ticktick
* [x] 创建8个基本 folder
  * 不需下一步行动
    * [x] 垃圾 -> Trash [ built-in ]
    * [x] 未来/也许清单 -> Someday/Maybe
    * [x] 参考资料 -> References
  * 需要下一步行动
    * [x] 项目清单（只存一个正在进行的项目列表） -> Projects 
    * [x] 等待清单 -> Waiting For/Pending
    * [x] 固定日期与时间：日程表/日历 -> Calendar [ built-in ]
      * subscribe to personal calendar about daily work
      * subscribe from work calendar about todos 
    * [x] 固定日期但不限时间：下一步行动 -> Next Actions
* [x] 自定义清单
  * [x] 想法清单
  * [x] 习惯清单
  * [x] 工作清单
* [x] calendar 如何只 subscribe 我同意了的活动？ -> Calendar 中可勾选去
* [x] 看一下现有的 folder，归类到8个基本 folder 里面，并进行基本增删改
* [x] 研究下利用 tag 来归类场景以高效化“下一步行动”执行的方案
  * [x] scenarios group: home, work, idle
  * [x] tools group: mac, mobile
  * [x] resource - spirit group: relax, middling, energetic 
  * [ ] resource - time group: none
* [x] 整理2017核心方向这个文件夹，否则就感觉只是把 Wunderlist 换了个地方用，毫无提醒执行作用 -> 产出一个 action，即是整理一下2017的年度计划，并按愿景 -> 专注 -> 可执行的行动这样制定出来
* [x] 整理下 Inbox 

要点是：

* 经过收集、清理、归档步骤后得到的“下一步行动”（action next）清单，不再计较其意义和必要性，而选择信任前面步骤的决定，避免重复思考
* “下一步行动”清单还需要进一步细化，需要有记录方式并体现在 Ticktick 中。依照资源限制的优先程度，分别是：
  * 场景（工作、生活、间隙、有没有电脑、在家、在商场等）
  * 资源：时间限制
  * 资源：物资、人力限制
* 日程表中的项目必做；下一步行动中区分 场景 和 精力；时间因素还只有人力区分
* 关于任务依赖关系的问题：如果依赖关系存在时间前后做的关系，只需设定日期即可；如果是同一天的任务，目前的解决方案如下，人为地：使用卡号表示属于相同任务（其实一个 story card 应是一个小项目，但是这里人为使用同样的命名前缀来区分也可以，不过模板脚本就得再自定制），使用数字来规定依赖次序。1-5 数字越小越先做，是其他的依赖，同样数字不存在优先级问题
  ![image](https://cloud.githubusercontent.com/assets/11895199/22852426/047924c2-f077-11e6-81de-42c28eb799b4.png)

下面我们来看一下一位超级会员的使用感受。

![image](https://cloud.githubusercontent.com/assets/11895199/22789438/dff92fde-ef1d-11e6-9072-54eba5d984cb.png) ![image](https://cloud.githubusercontent.com/assets/11895199/22789473/fd0e25c0-ef1d-11e6-8221-ec9adb33f502.png)

**Comment by JimmyLv** [comment]
镇楼：

![image](https://cloud.githubusercontent.com/assets/4997466/22816104/d09971f2-ef9a-11e6-93fb-9e6014439cec.png)

**Comment by linesh-simplicity** [comment]
快整理好 inbox 了，30个 item 得整理半小时啊…
