### ISSUE TITLE
域名创建

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#12]
根域名[linesh.tw](http://linesh.tw)。

**Comment by dudulism** [comment]
目前创建了两个子域名：

* 主博客：[blog.linesh.tw](blog.linesh.tw)
* 五子棋博客：[dudulism.linesh.tw](dudulism.linesh.tw)

close #12

**Comment by linesh-simplicity** [comment]
目前有两个子域名：

* 主技术博客：[blog.linesh.tw](blog.linesh.tw)
* 五子棋博客：[dudulism.linesh.tw](dudulism.linesh.tw)

close #12.

**Comment by linesh-simplicity** [comment]
说好的close即关闭呢。难道只有在commit中才生效吗。

**Comment by linesh-simplicity** [comment]
git tag -a v1.4 -m "Close #12" 也没用。
