### ISSUE TITLE
整理工作邮件，产出有益英文交流

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#125]
## TODOLIST

* [x] 产出整理源
* [ ] 分类整理源，筛选出可能有效信息含量最高的来源
  * [ ] 设置邮件分类，产出：
    * [ ] 高有效信息含量可能性邮件
      * [ ] Business replies - from key stakeholders 
      * [x] to StyleGuide team
      * [x] to DART team
      * [x] leaves 
    * [ ] 低有效信息含量可能性邮件，直接放弃搜集
      * [x] AWS instance launch
      * [x] JIRA card movement
      * [x] calendar invitation 
    * 其他
      * [x] PR reviews ( medium )
  * [ ] 产出 PR 要整理列表
  * [ ] chat history，产出：
    * [ ] 重点关注人物回复列表
  * [ ] JIRA 卡。优先级最低
* [ ] 产出重点关注的话题列表
  * [ ] 一般性意见表达（I think, ...）
  * [ ] 复杂的事情阐述
  * [ ] 不同立场观点互相说服
  * [ ] 关键性决定对齐
* [ ] 实际记录
* [ ] 产出成果，可能是：
  * [ ] MyTW 上文章
  * [ ] 邮件组文章
  * [ ] 博客

整理源
---

* 邮件
* chat history 
* PR
* JIRA 
* ...

每类下面可以整理出一些比较有代表性的看，比如邮件，可以重点阅读那些表达不同观点、对齐重要决定、英语较好的人回复的邮件；PR 可以只看理查德或皮大哥的评论等。

**Comment by linesh-simplicity** [comment]
没整理「完」，与 $**p 的缘分就到这里止了咯。

**Comment by JimmyLv** [comment]
为啥 leaves 会作为高有效信息含量可能性邮件？

**Comment by linesh-simplicity** [comment]
其实最后就是总结出了一个套路：

* for common users: 什么时候 leave，什么原因，什么时候回来，期间有事找谁
* for 大佬 users: 什么时候 leave，什么时候回来，期间有事找谁

哈哈哈哈
