### ISSUE TITLE
UI Community: React Camp

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#137]
- 本次集训包括每周一次，每次三个小时左右的大概五轮workshop(每周三或周四下午5点到8点)
- 内容包括React核心解析，周边生态工具讲解和练习，工程化项目实践，ReactNative实战讲解
- 旨在让参与者从初学者/普通开发快速成长，并熟悉工程化实践，未来能够Drive一个React项目

**Comment by JimmyLv** [comment]
我来给你补充材料，顺便充当聊天室啊这里。

两个 JavaScript 高阶语法参考：
[React on ES6+ · Babel](https://babeljs.io/blog/2015/06/07/react-on-es6-plus)
[React Native Express - ES6](http://www.reactnativeexpress.com/es6)

**Comment by linesh-simplicity** [comment]
哈哈哈哈哈，卧槽竟然刚创建 issue 你就来了

**Comment by linesh-simplicity** [comment]
无疾而终，最后真的只是去种了个草。关闭 issue ing...
