### ISSUE TITLE
健身笔记💪

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#144]
肌肉训练的两个理论，与刻意练习同出一脉：

* 超负荷练习
* 循序渐进练习

总结起来，提高要诀就是要刚好超出舒适区一点点。超过负荷了就退回来，直到能完全无压力做到新的负荷为止，再往前推进一点点。这个「一点点」的思维，又是取材于 TDD 小步前进的思想。

健身不在重量大小，重量本身只要刚好超出你的负荷一丢丢就足够了。健身效果在于，动作有没有做标准，有没有最大程度地刺激对应部位的肌肉。动作标准意义在于，减少对关节的损伤，提高对应部分肌肉的刺激效率。效率是什么？是做对应练习的时候，其他部位肌肉尽量不要发力支持。

练习方向：先练大肌肉群，会让整个身体看起来健壮一些。大肌肉群包括胸、背、肩、腿、手臂、腰等。

1 体测、极限测试、肱二头肌与胸肌练习
---

* 偏瘦；无机盐与水分略不足；其他正常
* 增肌需要从饮食与锻炼两方面。就像阳光和水嘛（没有想到教练也有小清新的范儿😂），缺一不可。饮食上，水分你懂的；无机盐主要是水果；推荐少量多餐。饿了就吃
* 🏃，脚后跟先着地可以减少缓冲
* 身体锻炼的原理与刻意练习的原理其实很像：一次只锻炼一个部位，并且每次要稍微超出你的舒适区/极限一点点
* 教练的作用三个：帮你刻画极限；教你正确的动作；帮你做刻意练习计划；
* 很多练习动作有共同点：分发力和束力部分（我自创的），发力部分可快可慢，但束力时一定要慢，对肌肉负重训练作用才能起到；发力时一般呼气，束力时一般吸气；一般双脚都与肩同宽，平行站立，**一定要目视前方**，**一定要抬头挺胸、背挺直**。目视前方可以看到自己动作，抬头挺胸一来保护脊椎利于发力，二来精气神好；后者我觉得从气质上更为重要，不要练得很猥琐…
* 特别注意手腕的动作，目前减少使用手腕发力
* 一般练一个动作，只要训练的部位发力，身体其他地方不动，这也是抬头挺胸的重要性。前期力量不足时很难做到，但动作一定要练规范

2 肱三头肌与背部练习
---

* 对力量更有控制以后，就可以控制发力的部位。练哪哪发力
* 就健身这个活动本身而言，我觉得一定程度还是带上了中产阶级的影子。不管是什么阶级，总之是有阶级的影子，我不希望沉溺其中。加入了运动，身体上精神会逐渐变得更好，更阳光，更有精力，这也是值得的“投资”。另外，我觉得心态要更加开放，接受多样的解决方案、不同的观点、生活方式。希望这种开放的心态，能尝试参加以前觉得不敢做的事情，有些一直想做的事，读诗、弹琴、阅读、写作，越不同的生活方式，越带来不同的眼界，期望尝试，而不仅仅是被消费。我觉得我的特立独行还不是很有力量，想要通过非阶级的方式来训练它。没有功利地
* 关于眼界这个东西，尝试更多了解世界的多样，更高的解决方案，更多样的生活方式，了解自己想要的节奏和能力。不要为一时的、眼前的得失，坏了一份好味道。感觉太阳这边团队之间各自为营，“推锅”玩得越来越心安理得，包括我。做一件事，不是说值不值得、能不能做，而是属不属于我做。俗气。说是有人的地方就有江湖，我想要有力量来调戏这江湖

3 胸大肌与腿部练习
---

* 注意到练习是不断向上提高剂量、减少次数 以突破负重量的
* 练习有一些原则，即尽量只训练特定的部位，很多时候做不到，但是尽量。比如仰推的时候，杠铃是在胸线直上直下的
* 负重半蹲、深蹲的重心在前面膝盖之间，两腿幅度要一致

4 肩背练习
---

都忘了 =。=

6  肱二头肌与背部练习
---

* 二头肌力量太差，要多练
* 每次去可以练练上上次的内容，让最近训练的肌肉群休息，同时唤醒上上次的练习记忆
* 练习一般四组，第一组的重量必须非常轻，为的是要把动作做顺畅，形成正确的姿势和感觉
* 杠铃练二头肌的姿势：脚与肩同宽（as always）；大臂夹紧；小臂不要夹太紧。体会只用二头肌发力举起杠铃的感觉，身体其他部分不发力。记得练时还有些不对的地方，忘记了，是说身体可以稍微前倾还是后仰来着
* 哑铃练二头肌的姿势：脚与肩同宽；大臂夹紧；小臂不需要夹太紧。哑铃垂直地面，先旋转至与地面平行，再使用二头肌发力举起至胸前，缓缓放下。注意身体不要晃（还是需要更大的力量和发力点来控制），特别是不要使用肩膀、三头肌带动辅助发力

7 肱三头肌与胸肌练习
--- 

首先，又有一个重要的事情了：**所有的动作都要求抬头挺胸背打直，为什么呢？一是保护腰和其他关节，二是固定身体不必要发力。这样可以减少受伤可能，增加其他肌肉练习效率**。

* 胸肌的练习，要确保确实是胸肌发力，而不是其他部分发力，比如手臂、三头肌等。以窄握卧推为例，握距可以稍微宽一些些，手臂拉到与胸垂直处，这样胸肌会被拉伸训练到。这个动作真是超神了，我觉得很难，做不太标准，身体忍不住会晃
    ![](http://t3.qpic.cn/mblogpic/db6b1fdf43adc8ec3ec8/2000)
* 俯立臂曲伸。这个动作，肩部尽量保持平直，肩膀和三头肌尽量锁死，只靠三头肌发力。
    ![](http://ppvsqq.com/upload/2014-12/1412011300405228.gif)

8 丧心病狂的练腿… + 腹小练习
---

为什么说丧心病狂呢，因为两天前刚爬完峨嵋回来啊！

* 练腿，脚留三分之一的空，主要是让前脚掌发力。关节一定不能锁死，锁死就是用骨头在支撑发力，重量加大一定不行，至少肯定会伤膝盖和关节。锁死的后果，感受一下：https://bbs.hupu.com/18835664.html
* 因此，所有动作，包括手和腿的，关节都一定不要打死，留一点点。留着就还是使用肌肉在控制发力，练的就是肌肉，对的，并且骨头关节都不会参与发力，不会有损伤
* 昨天练大腿举的时候，感觉左腿膝盖有点痛，可能是有些动作没做对，我想想
* 还是一练腿的动作：脚与肩同宽。右腿往前**迈**出一步，脚尖向前，左腿脚尖也要往前，体会这个迈出的感觉，后面的腿不要往外撇。迈出至大小腿成90度角，后腿蹬地收回；左腿依此
* 腹肌不急着练，据说它要求周围很多肌肉群的力量，因此训练顺序应该在较后面

9 肱二头肌 + 背部练习
---

二头肌练习真是爽。换了个教练，在每一组的练习当中就会给出反馈，会减少重量来固定动作的标准姿势，更多的鼓励和交流。比较不错。

* 类引体向上的动作，只不过腿下方有支撑。我理解，可能是为了减少腹部发力，专门练背部。这节课提到一个新的概念：**握距**。 练的时候一定要保持双手/脚握距相同，为何？保证两边的同时发力嘛。这个动作，腿跪到支撑板的二分之一处即可，因为身体要往外，给背部留出垂直向上发力的空间。然后说关键的手：手可以稍微往前屈一丢丢（大概5度），尽量垂直于地面和身体。为何？往前屈太多或者往后压都会导致肩部的发力，降低了背部发力的效率。要体会这个背部发力的感觉，其他部分少用力。当然，做完我感觉整个小臂都挂了。还是会有很多小臂发力的部分，可能是因为身体重量本身还不是单纯背部能够承受的重量范围，所以小臂必须辅助发力了。这个动作可能需要使上肢力量与背部协调了以后，练起来比较有效果
* 原来这叫坐位下拉。练肩背的，有图太棒了。腿要顶着前面的护垫，下半身固定不动。拉下来的时候吐气，放上去的时候吸气；一说都要尽量匀速，一说拉下来的时候可以快点（因为它用到的主要不是肩背的力量），放的时候一定要慢慢放。这个动作对斜方肌和小臂都有作用。重要的点来了：身体大概倾斜15到20度，保证拉下来的时候不要磕到鼻子👃；小臂尽量往里收，这样可以带动背部肌肉收紧发力，起到更好的锻炼效果
    ![image](http://t3.qpic.cn/mblogpic/5a7b05b0db3406976ce8/2000)
* 前臂屈/杠铃弯举，练习二头肌，是我最喜欢的动作之一，对二头肌和小臂内侧的刺激特别大，爽得飞起。**抬头挺胸背打直，肩和大臂往里扣夹，不能动**，两臂贴于体侧，这样整个身体都固定了，支撑二头肌和前臂的发力。尽量不要动大臂（动也可以，是另外的练习），手腕不要往里扣，就只使用二头肌的力量把杠铃举起
    ![image](http://t3.qpic.cn/mblogpic/7551804d3b31f06baeca/2000) ![image](http://ppvsqq.com/upload/2014-12/1412011300405210.gif)
* 俯坐弯举。大臂贴于大腿内侧，不动，不发力，弯曲二头肌把哑铃举起。
    ![image](http://ppvsqq.com/upload/2014-12/1412011300405225.gif)

10 三头肌、胸练习
---

* 不少胸部练习的动作需要三头肌助力，因为手臂需要屈伸，所以一般这两个部位一起练，可以连带提高
* 新教练的路数很好：不上太大重量，先把动作做标准；坚持不了的就辅助。动作标准了以后，按照刻意练习的原则，加重量+减次数循环递进练习。动作标准有两大好处：减少损伤；减少无关部位发力，增强肌肉控制力，增强发力点感觉，提高锻炼部位练习强度与效率
* 双杠双臂屈伸：类似于双杠的动作，只不过腿部有支撑，所以腹部不需发力，胸部发力减少，主要练习在三头肌。肘关节尽量往里面夹，起固定作用；小臂下降不一定非得到90度垂直，只要感觉三头肌在发力、很紧了就可以。这个动作我感觉很多其他部位都在发力，比如腹部，肩部，胸部，感觉不对劲
* 坐姿屈臂夹胸：我喜欢的动作之一，胸肌夹感强烈。坐直，抬头挺胸；使用胸肌夹紧发力，同时吐气。手肘稍往外展，尽量与胸部齐平，细微之处自己调整，但主要是要让胸大肌拉伸、收缩夹紧发力
    ![image](http://ppvsqq.com/upload/2014-12/1412011300405220.gif)
* 卧姿哑铃胸举：这个动作跟杠铃卧举一样，我觉得对全身力量要求较大。教练说做不了就做单边，上4kg，确保姿势正确为先。这个动作的精髓在于，使用胸肌向上「夹推」发力。因此，哑铃的位置，必须与胸在同一平行线上，这样才能让胸肌发的力「向上」将哑铃举起，避免身体其他部位发力；比如，位置靠胸线下，则手臂要辅助发力；位置靠胸线上，则肩膀要辅助发力；效果都将不是很好。此外，三头肌也会参与发力，还挺酸的
* 三头肌拉力练习：不知道怎么叫这个器材。站直，身体可以稍往前倾；胸背打直往后收，夹住大臂。使用三头肌发力将绳索拉下，肩、斜方肌、大臂均不用力；注意不要耸肩辅助用力，大臂不要往下往后辅助发力。大臂固定不动，夹紧于两侧，这形成了一个发力支撑，只使用三头肌力量练习
* 弓步屈伸胸部练习。 最后一个练胸的姿势，最后一组加4.5kg就比较吃力了。弓步，身体压下20到30度，手肘稍微提起至与胸大概平行。发力夹胸即可。注意，肩部固定不发力，只作为轴转动手臂；大臂小臂三头肌不要辅助发力；弓步蹬直利于发力。避免爆发力拉下，使用胸肌发力慢慢拉下，感受夹胸的发力感，其他部位不发力是关键

http://ppvsqq.com/show.aspx?id=54809&cid=59

* 二头肌目前平均负重每边 10lb/4.5kg，总负重 20lb/9kg;
* 卧举哑铃（胸肌）平均负重每边 9lb/4kg，总负重 18lb/8kg；
* 坐姿屈臂夹胸总负重 44lb/20kg
* 三头肌拉伸练习：不负重
* 弓步屈伸胸部练习：不负重，最后一组 10lb/4.5kg 10个
* 双杠双臂屈伸：貌似是上一格重量，23lb/10kg

**Comment by JimmyLv** [comment]
卧槽，这可以的！
