### ISSUE TITLE
P1: Classic Arcade Game (III) 课程直播

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#148]
直播内容准备大概7小时。前期准备半小时，和 will 聊一下1个小时，自己准备核心内容3个半小时左右，准备讲稿和 PPT 半个小时，实际讲1个小时，总用时大概6小时50分。

Outlines
---

### 任务分解 Tasking 

* **Tasking 是什么**? 
  * 是一种做事的方法论，提供条理性
  * 产出：任务列表 + 工作流
* **为什么你需要 Tasking**?
  * 你要做什么事
  * 怎么知道你做完了
* **如何 tasking**? 
  * 从源头了解需求
  * 归类需求，产出任务列表

### 快速反馈 Feedbacks 

* **是什么？**
* **为什么要快速反馈？没有会怎么样？**
  * 及时地修正调整
  * 缩短调试周期（Will：就像建筑，上面的每一层都搭建在下面很坚实的基础上）
  * 增强信心
  * 保持注意力
* **如何获得快速反馈**  
  * 例子

收获
---

* 自己直播真的是学习的很好方式！对于你要讲的知识点，有这些自己学习的时候没有覆盖到的问题：
  * 是什么，如何使用比喻通俗介绍（有时自己并没有深入思考，只是听过，已经有上下文，所以能理解）
  * 为什么要用它（这大概是大家学一个东西都很关心的一个东西）
  * 怎么用 / 怎么做
  * 听众可能有什么问题，自己去思考，然后和原来的知识体系重新编织到一起
* 没有人提问题和反馈……我原想着大家会比较积极的，有很多部分可以和同学一起聊，激荡想法，结果问完第一个问题没人回答以后，我就发现微妙的气氛。后面就适当减少了互动。看来还是要学习互动的方法

# 准备过程👇

5P 原则
---

* purpose: 
  * 没有完成的同学：分享一下思路，remove blocker。不会单独解决问题，而是通过一个 general 的流程（博客）把中间可能经过的一些阶段覆盖到
  * 已经完成的同学：分享一下思路，互相学习
* product: 
  * 没有完成的同学：获得了解决问题的思路
  * 已经完成的同学：了解了任务分解的工作方式，及快速反馈的思维方法
* people: 
  * 所有参加了前端进阶课程的同学，可能会来听现场，也有可能回过头看录像
  * 导师？
* pitfall: 
  * 观众注意力可能只有20-30分钟左右：以图、代码为主，分享概念
  * 不要太注意别人看法，要“点燃自己”，讲出激情和想讲 @sunshawn16 
  * 没有人回应：缩短互动时间，自己接过问题就可以了
  * 有不同的看法：自己掌握着直播的“公权力”，说话观点务求尽量中立客观，不偏袒，不安利，
  * 视频：看不到
  * 画面共享：同学看不到
  * 宿舍网不好：出现的几率比较低，但解决方案：不露脸，只分享屏幕；手机热点分享
  * PPT：以图为主
  * 「上次 rehearsal」OO - 面向对象；可能同学会对这个词没有听说过，可能对面向对象的设计方式不是很了解。解决方式：使用中文“面向对象”，不要用英文
  * 「上次 rehearsal」暂时把所有材料切换到中文版本
  * 「上次 rehearsal」保证所有的链接可用
  * 「上次 rehearsal」尽量不要涉及具体代码的实现，所有的代码尽量只用伪代码实现

开场
---

* Ground Rules: 
  * 随时提问
* Ice Breaking: 自我介绍
* Parking Lot: 什么不讲
  * ES6
  * TDD
  * 刻意练习
  * input-output、定义核心功能、快捷键等？

Process
---

总流程1个小时。我的部分可能会有30~40分钟左右。

### 开场（5-10min/3min）

* Will 开场+介绍 purpose，然后会把主题和我引出来
* Linesh 自我介绍（2min）
  * 大家好，我是前端进阶课程的学员 Linesh。（不介绍公司、工作年限、职位和工作方向，因为不安利）今天很高兴能够在这里和大家分享我完成作业的一些心得。

### 转场 + 进入主题：tasking 和快速反馈（1min+2min+1min）

* 今天我想和大家分享的更多是完成这道题目的思路，不过由于这个思路其实有一定的通用性，所以大家不仅可以使用这些方法去分析这套题目，甚至都可以尝试把它应用到其他的编程任务中去。今天，我要分享的主要有两个点，开始之前想先问大家一个问题，不管是已经完成了还是正在做，或是还没开始的同学：拿到这个项目，你第一件做的事是什么？……拿到这个项目，你第一件做的事（会）是什么？给1到2分钟的时间，大家可以在下面留言
* 答案尽量给予肯定。例：xx 不错不错，还有吗？xx 也很好，还有没有其他的回答？（真是有九指老师讲课的感觉）「一两分钟到」很好，很好，大家说的都很好啊。有说 xx 的，也有说 xx 的。都不错，都有道理。我可以分享一下，我拿到这个项目第一件做的事是什么。**任务分解**啊。

#### 什么是任务分解

是一种做事方法，提供了做事时的条理性。我们做任何事情都应该划出 **任务列表**（产出），按照列表一项项去完成（工作流）。所以，任务分解的工作流其实就是：

1. 产出一个任务列表
2. 按照列表上的任务一项项地完成、打钩

那么，为什么我会选择最先做任务分解，而不是先去写代码或者思考设计呢？（这不是什么特别稀奇的工作方式。然而问题是，很多时候我们列出的任务列表不能达到完全穷尽，各自独立。http://insights.thoughtworkers.org/programming-method/）

#### 为什么要做任务分解

它解决了两个问题：即 **你要做什么事** 以及 **你怎么确定你做完了**。

* 如果不知道要做什么事，我可能就会多做或者少做一些本来应该做的事，在提交代码以后因为没有完全全部的需求被打回来（其实我还是被打回来过一次的哈）
* 如果不知道怎么样就算做完了，那就有可能我以为我做完了全部的事，但其实有所遗漏

对应到其他工作或者其他编程任务中也是一样的，定义任务范围、定义完成标志，都是重要的事。通过任务分解，我们会产出一个任务列表，这个列表就定义了所有要完成的事情，所有不在上面的事情一律不做，然后我一项项地把它们完成、打勾，当这个列表全部勾完的时候，我就可以非常确定地说，我的任务全部做完了。http://discussions.youdaxue.com/t/classic-arcade-game/36088

#### 怎么做任务分解

没有什么特别办法，重在实践练习。不过有两个建议：从源头出发了解需求，然后归类需求。下面我们就以这道题目为例子，分享一下我是怎么做这个编程项目的任务分解的。

* 阅读原始需求：
  * https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/82ba869b-bb0a-4ce8-847a-b59c6935ee05/modules/bae316ce-be90-4d30-b864-55d65207aa8c/lessons/2696458597239847/concepts/26849785360923
  * http://discussions.youdaxue.com/t/topic/32577
  * https://review.udacity.com/#!/rubrics/499/view
* 分组归纳
  * 前置工作
  * 核心功能
  * 边界检查
  * 样式要求

### Tasking 部分答疑（2-5min）

* tasking 和甘特图等有什么区别？
* 怎么样是好的 tasking？-> 完全穷尽、互相独立。（此时也可以让同学来帮忙回答，同学们怎么想？有没有同学可以帮忙回答一下 xxx 同学的这个问题？不过自己要懂得把话题拉回来。然后实践了一下，发现同学们不会来回答，因而也就不会抢回答）
* 有没有什么工具辅助 tasking？
* tasking 的正常工作流是怎样的？ 产出任务列表 -> 一项一项完成
* tasking 是不是一件必须的技能？没有了它行不行？也许行，但不快，质量不高。没有它，你要么需要占用大脑的一个进程来追踪它，要么你就没有该做什么的概念混沌中来混沌中去。
* 有没有见过不会 tasking 但代码写的很好的程序员？大🐻答。没有
* 有没有数据显示 tasking 真正提高了效率？这是一个好问题。我的基础设施搭建刻意练习成绩。但这里我还运用了其他的技术——戴明环 PDCA——来记录用时、分析弱点、刻意练习提高。再次引入仝健的这篇文章：http://insights.thoughtworkers.org/programming-method/

### 主题二：快速反馈 Faster Feedback

* 好，那么任务分解这一块就聊完了，接下来我想和大家分享另一个话题：快速反馈。首先还是先问一下大家，大家觉得这个快速反馈是什么意思？有什么作用呢？

#### 什么是快速反馈

快速反馈就是，你做的事情，很快就给你结果以反馈。比如说，你打游戏的时候，砍一下敌人，敌人马上就掉血了，同时可能还有视觉上的一些反馈；比如说你练琴，按一下就可以听到声音；比如说你练习投篮，投一下进没进马上就可以看到，等

#### 为什么快速反馈很重要

* 根据快速反馈调整学习路径，马上可以得到反馈的事情可以让人知道与目标之间的偏差，从而快速修正调整；此外，快速反馈也可以为学习带来肯定和信心增强、保持注意力和热情等。比如弹钢琴，假如你按下一个琴键需要一天以后才能听到声音，你还能学会弹钢琴吗？假如你 q 一下别人，要30分钟才能看到 ta 掉了多少血，你还会玩 LOL 吗？假如你开一枪要等30分钟才能看到对方有没有被爆头，你还会玩 CF 吗？假如你写的代码需要运行30分钟才能看到结果，你能等上30分钟吗？你还有热情和兴趣记住30分钟前做了什么更改吗？假设30分钟等到的却是一个错误提示，你会不会感觉很沮丧呢？
* 因此缩短反馈时间、得到更快速的反馈是很重要的；我们尝试把这种反馈时间缩短到极致，每写一行代码就要得到反馈。有的同学可能会问，是不是太极端了？有必要每写一行代码就验证一下吗。当然，这个可以视你自己的信心和经验来裁剪，总的指导原则就是，步子不要太大。

### 怎么在项目中实践快速反馈的思想

带着做快速反馈这一块。

### 快速反馈 部分答疑（2-5min）

* 有些技术确实没有办法马上得到反馈怎么办？比如 ansible？比如编译型的程序？那这是领域特定的问题了嘛，以这个思路去尝试搜索解决方案，如果没有，那确实是一个有待解决的痛点。可以讲自己当时缩短 tomcat livereload 时间的例子（20min -> 2min）

### 其他部分

人物移动、碰撞检测等。

**Comment by JimmyLv** [comment]
Really? I will be the first one to attend this

**Comment by linesh-simplicity** [comment]
啊咧，是的，打算走一波直播~毕竟直播也是学习的好方法~

**Comment by JimmyLv** [comment]
给谁直播呀？哈哈哈，斗鱼么？

**Comment by linesh-simplicity** [comment]
啊咧，课程每周会有一次面向报了课程同学的直播，主要就是分享、解答这周学习的疑惑咯。一路顺风~

**Comment by linesh-simplicity** [comment]
视频录像还没出来。到时再回看一遍，有需要的话更新此卡。今天“迭代”结束，关闭此卡。
