### ISSUE TITLE
更换markdown引擎为kramdown

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#15]
github5月1号后将只支持kramdown引擎：https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/

**Comment by dudulism** [comment]
close #15

**Comment by linesh-simplicity** [comment]
close #15.
