### ISSUE TITLE
API 玩起来

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#169]

**Comment by JimmyLv** [comment]
![image](https://cloud.githubusercontent.com/assets/4997466/26285154/a2652304-3e7c-11e7-91e9-bab44ab6c0ef.png)

**Comment by linesh-simplicity** [comment]
@jimmylv 它自个就出来的…

**Comment by linesh-simplicity** [comment]
这个应该是 Zenhub 搞的鬼。
