### ISSUE TITLE
4.4 如何快速熟悉一个项目

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#174]
本文系从 [郑烨的“加入项目需要了解什么”系列](http://dreamhead.blogbus.com/logs/224229646.html) 演进而来。文章细化了各个层级需要了解的内容，并提供了具体而细致的了解次序。总的思路是：大面上从业务到技术；业务上从核心到边缘功能；技术上从架构到部署到具体模块。

在**Thought**Works同事经常需要在不同项目上快速流转这个背景下，希望本文能提供一些具体的套路。也欢迎各位同事提意见完善这个清单。

## 目录

* 总的要了解的内容
  1. [业务与产品](#业务与产品)
  2. [组织结构与干系人](#组织结构与干系人)
  3. [技术选型和架构](#技术选型和架构)
  4. [团队工作方式与工具](#团队工作方式与工具)
  5. [技术细节](#技术细节)
  6. [项目现状与改进](#项目现状与改进)
* [了解的次序与落地](#了解的次序与落地)
* [总结](#总结)

## 业务与产品

> \#1 系统是做什么的？用户都有谁？系统解决了他们的什么痛点？系统为他们带来了多大的价值？

> \#2 (如果是2C产品) 同业里竞品是什么？本产品与其相比的优劣？
> \#2 (如果是2B产品) 本产品在集团中位置如何？为其他团队提供服务否？

> \#3 系统最主要的（产生业务价值最大的）功能是哪几块？哪几块是当前活跃开发的功能？哪几块是边缘功能？

> \#4 本产品愿景是什么？中短期有什么需求、计划？

> \#5 团队如何获得真实用户的反馈？团队如何获得新的需求？

> \#6 团队有没有prod上的数据运营平台？团队如何（何时何人）对运营数据进行分析统一、产出洞见？这个获取反馈-转化为新一轮实践验证的周期多长？

## 组织结构与干系人

> \#1 项目的TL、PO、PM角色分别是谁？

> \#2 该公司组织结构如何？该项目向谁汇报？该干系人对项目的要求、诉求、利益关系如何？项目成败由何衡量？是关键人（某总）的主观评定、抑或有何客观指标？若有指标，如何获得？

> \#3 该项目隶属于组织结构中的哪部分？该小组织在大组织中的位置是什么？

## 技术选型和架构

> \#1 项目主技术栈是啥？架构选型与核心技术所应对的业务挑战是啥？核心技术部分如何架构？
>  * 核心架构。比如前后端分离/微服务、事件架构、发布-订阅、埋点等的技术架构与工具选型
>  * 主技术栈及框架。比如前端用React/Semantic，后端NodeJS+Express等，详见框架搭建
>  * 三方库。瞟一眼`package.json`就行，此时不用深究，用到再研究

> \#2 应用形态：前后端分离是仅仅技术分离还是团队人员也分离？大单体还是微服务？单体数据库/共享数据库？这关系到团队内部、与其他团队之间的合作方式

> \#3 **读一下系统架构图，了解包括各个环境的机器部署拓扑结构、系统架构等信息**

> \#4 **系统的三方依赖（被本系统需要、但不归本系统维护的三方系统）：** - 通常有文档
>  * 系统总的三方依赖图，都有哪些？它们各自为系统的什么部分、提供了什么数据？
>  * 对于每个依赖，搞清楚它们的：接口人是谁？通过什么方式与他们沟通（聊天群、邮件等）？产品有没有文档？他们与本单位的关系？承诺程度如何？开发和发布计划与我们对齐否？质量问题等如何管控？开发周期如何？出现质量问题时解决周期和接口人？

## 团队工作方式与工具

> \#1 团队的工作流程怎么样？都有啥角色？如何获取需求？如何验证需求（kick-off）？如何开卡？如何测试？如何联调？如何验收？验收标准是什么？分别有多少套环境？在什么环境上做什么事？

> \#2 具体到做卡，估点按人天还是比例？是否按TDD方式开发？有没有单元测试和lint？测试覆盖策略如何？VCS工具是啥？代码提交到主干还是分支？是否需要PR？如何在本地启动应用验证？本地是否有Hot Reload等开发者体验的工具？

> \#3 部署：如何部署到测试环境、UAT环境？部署流程是全自动化、一键触发，还是手动进行？部署production前是否还有额外工作要做？

> \#4 迭代周期、敏捷流程（CR、三大会等）

> \#5 团队对技术卓越、持续改进的实践与意愿如何？

> \#6 各个流程的工具链：使用了哪些工具来支撑本地开发、构建流水线、部署流水线、机器监控页面、应用监控页面、电子卡墙、Wiki页面、沟通工具、邮件，以及其他的流程管理？

> \#7 对于一个典型的横跨各个层级的feature一般如何实现？比如，通过调用一个后端API把一个简单的字段在前端进行展示、从三方API中获取一个新字段并保存到应用中通过GraphQL暴露展示到前端，这样的简单任务。

## 技术细节

> \#1 代码层面的**目录结构如何？实现架构如何？与高层级的系统架构是否容易建立对应关联？**。看看项目的主要模块，以及模块之间的引用关系？模块间协作关系如何？（以前端为例，就是看项目如何组织action/reducer/effects，如何组织UI组件/业务组件/公共组件等）

> \#2 了解一下**多环境策略 - 构建/部署流程以及代码层面如何协作以支持多环境配置？构建脚本是否都被完整地提到了版本管理中（基础设施即代码）？**

> \#3 **系统内部主要的数据模型是哪些？哪些是核心表？将它们的用途与应用的业务关联起来。它们主要服务于存储、UI还是兼具？哪些表之间存在着（什么样的）关联关系？如何引用（特别是在文档型数据库中）？** - 这个一般可通过通读一遍数据库模型得知

> \#4 **系统各个三方系统为本系统提供的数据内容，阅读用到的API列表及其请求/输出内容。** - 数据内容和服务地点一般有系统架构/依赖图就可一览无余，API列表及其输入输出格式一般可通过查询日志界面（诸如`access.log`/Kibana UI之类的东西）得知

> \#5 **了解系统的核心/主要业务。**
>  * 优先参考自动化测试导出的测试报告（`.csv`/`.xlsx`）间接得到业务列表；
>  * 其次可通过应用集中化的配置文件通读架构或业务（比如路由表`Router.ts`、事件表`tradingEvents.ts`等）
>  * 再其次看死的文档

> \#6 读一下项目的Support页面，了解常见的频繁出现的Support任务有哪些？具体需要如何操作？能自动化否？支持时如何从日志界面中查询常见的日志？这些常见查询有什么简便的获取办法？

> \#7 通读一下核心业务的实现代码

> \#8 系统的自动化测试策略如何？每层的侧重点是什么？策略是什么？（是否mock数据库？是否mock API？等）策略能否完整地覆盖所有的代码，做到敏捷原教旨主义的“没有代码不写测试”？测试策略高效否？本地测试速度是否快？本地与CI跑的结果是否一致？有啥还可以提升的东西？

## 项目现状与改进

> 项目做的好的实践是什么？能提供的良好环境是什么？

> 项目的业务痛点、技术痛点都有啥？哪些痛点最重要、最有解决的价值？团队已有什么调研？

## 了解的次序与落地

建议的次序一般是这样：

* **先找BA或PO从业务角度了解下项目**，这可以回答[“业务与产品”](#业务与产品)一节的全部问题、[“组织结构与干系人”](#组织结构与干系人)中的问题#1；
* 对于[“组织结构与干系人”](#组织结构与干系人)中的问题#2和#3，宜侧面打探；
* 自己花时间了解下[“技术选型和架构”](#技术选型和架构)，了解项目全貌利于开始写代码；
* **最好能与团队成员结对完成一张简单的故事卡**，这可以了解[“团队工作方式与工具”](#团队工作方式与工具)部分的全部问题
* 自己花时间了解下[“技术细节”](#技术细节)部分未在前两步中解决的疑问
* 最后了解下[“项目现状与改进”](#项目现状与改进)部分的问题，了解自己可以为项目做的贡献

## 总结

上面这个套路，反过来也提出了一个“好项目”的部分衡量标准：当有新同事进入/接手时，能多大程度地给他所有需要的信息、帮助他快速熟悉并产出？从各个部分来说，比如：

* 项目有没有高层级的文档记录**机器与环境拓扑、系统架构、三方依赖**等？
* 是否具备自动化的**多环境策略**？是否做到了**构建脚本与部署脚本的基础设施即代码**？
* 是否具有自动进行**自动化构建、自动化部署**的环境设施？是否有一键部署的上线流程？
* 是否具有**一致的高层级架构与代码层面的目录/实现架构**？
* 是否具有**不同层次且覆盖完全的自动化测试，并做到测试即文档**？
* 是否能一键安装本地环境（包括依赖、工具等）？是否能一键启动本地开发环境？
* 是否有文档记录**常见Support工作及流程、release流程、测试账号密码**等需要手动传达的信息？

下个系列，打算写写：作为TL应该如何搭建一个新项目，以及inception的主要流程及checklist。

## 参考文章

* [梦想风暴 - 当我加入项目时，我要了解什么](http://dreamhead.blogbus.com/logs/224229646.html)
* [梦想风暴 - 当我加入项目时，我要了解什么（二）](http://dreamhead.blogbus.com/logs/271835186.html)

**Comment by Kevin170113664** [comment]
文章开头的链接已失效

**Comment by linesh-simplicity** [comment]
![image](https://user-images.githubusercontent.com/11895199/38169012-6fdb7bde-3590-11e8-9358-9ebfaf963fde.png)

**Comment by linesh-simplicity** [comment]
@Kevin170113664 现在来看，觉得这个 list 有些乙方的固定思维，缺乏一些产品视角。

**Comment by Kevin170113664** [comment]
@linesh-simplicity 如果有产品视角，那么会是怎么样的呢？

**Comment by linesh-simplicity** [comment]
比如说，我觉得的产品视角就是说，我这个东西是给人用的，它必须是产生了独特价值的。那么我就会问类似这样的问题：

* 团队如何获得真实用户的反馈？如何快速获得这个反馈（例如持续集成、功能埋点等）？团队从获取反馈到转化为新一轮实践验证的周期多长？
* 产品的价值点何在？愿景何在？团队是否认可并围绕这个产品价值行动（开发特性、构建技术实践）？
* 团队如何知道自己在做正确的事情？团队是否一直坚持做正确且有价值的事情？团队的驱动力来自于领导，还是流程，还是这个价值观？
* 团队进行回顾改进的频率多高？

**Comment by JimmyLv** [comment]
@linesh-simplicity 这篇文章换个角度，也可以转化为「如何让新人快速熟悉一个项目？」

啊哈，一个项目上的老人所总结出来的资料，确实会缺失一些新人的角度，踩过的坑也可能忘记了。

**Comment by linesh-simplicity** [comment]
啊哈哈哈，很有道理。我现在分为两部分，一部分是代码和项目结构可以自注释的部分，一部分是需要简要 document 的地方

## 可以自注释

* 良好的目录结构
    ```shell
    .
   ├─ src
   ├─ ci
   ├─ scripts
   ├─ packages
   ├─ package.json
   ├─ index.js
   └─ README.md
    ```
* 良好的架构
* 骨架代码遵循入口+索引的结构（比如 redux、saga、router 都有对应入口可找）

## 需要 document

* `package.json` 里的脚本（构建、部署）入口

**Comment by linesh-simplicity** [comment]
@jkvim 有什么补充随时填上

**Comment by linesh-simplicity** [comment]
上面这个套路，反过来也是给你的项目做得好不好提出了衡量标准：「当你离场时，除了已完成的需求，你希望接手的同学看到什么东西？」同时，它给这种业务型的项目如何编写 README 也提出了衡量标准：

1. 如何启动项目？有没有一键式脚本？`npm install && npm start --env=sys`
2. 项目技术架构能够让人一目了然到几乎没有学习成本？
3. 已完成的需求，有没有自动化的测试套件，或手动的回归列表？
4. 测试环境账号和数据？
5. 常用链接和账号？

**Comment by linesh-simplicity** [comment]
然而这个list在尝试解决“快速了解项目并能快速对项目作出贡献”方面，于我当前这个项目对我帮助并不大。是因为郑烨overview和局部技术落地能力比我强所以有用，还是因为我执行不到位所以没用，还是这个list本来就没能达成它想要的目标呢？

另外，这个列表具有非常浓重的敏捷、工程化的导向，假定它有效的基本前提其实是：“软件项目中的大部分都不是技术问题，而是协作问题”。虽然做到“每日上线”很了不起，也需要很强的工程能力配套，遗憾的是它并不需要太强的编程技术本身的能力。框架、库、前期架构已经帮你解决掉99%的问题。那么作为开发者的我们，每天在做的事情究竟有啥了不起的呢？

**Comment by JimmyLv** [comment]
Phodal 的文章，[【新项目检查清单】帮你规范开发流程 - 知乎](https://zhuanlan.zhihu.com/p/59697431)

以及在线检查的工具 [New Project Checklist - ✨ Your best Project Tool ✨](https://phodal.github.io/new-project-checklist/)

我觉得还挺不错的，提炼&抽象。

**Comment by linesh-simplicity** [comment]
我的同行们怎么都这么优秀！！！这俩清单太棒！

还有个 Tech Lead Inception Checklist，简直已经没有没被思考过的问题…

https://github.com/gigix/jungling/blob/master/InceptionChecklist.png

**Comment by JimmyLv** [comment]
9年前…… 我的妈呀，🤣

**Comment by linesh-simplicity** [comment]
偷一张大熊的图：https://github.com/gigix/jungling/blob/master/InceptionChecklist.png?raw=true

![Inception Checklist](https://github.com/gigix/jungling/blob/master/InceptionChecklist.png?raw=true)

**Comment by linesh-simplicity** [comment]
更新了文章。

打算更新到博客，然而发现博客详情页挂了……啥时候的事儿这是…
