### ISSUE TITLE
翻译《持续集成将死》一文

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#183]
* https://zhuanlan.zhihu.com/p/27073836

哈哈哈。

翻译流程：

1. 通读，边读边变成口语化中文；
2. 润色难句与不通顺处；
3. 译出原著观点、倾向与灵魂所在；
4. 最终的格式校对、排版、链接、引用；

其实仍是单一职责原则的工作论。通读部分，使用尽可能快的速度译出80%的篇幅；润色部分处理剩下难点；原著倾向性其实是作品本身的灵魂所在，这个汁味应该是翻译者应该有所想法和追寻的。错字可以随手修改，排版、格式校对等样式问题，最后统一处理，不要一边翻译，一边校对标点符号。

这里处女座的细心可以帮到一些忙：在翻译阶段，其实大部分的错字、标点不匹配都会在第一时间被找出，留到后面的会很少（不到1%？），这样在翻译过程，糟糕的标点和样式对审美造成的干扰确实很小。这需要工具的支持，比如输入法、编辑器、快捷键等。所以才说，一个与自己工作习惯无缝衔接的 Mac 系统才如此重要，随着时间增长，它带来的作用会越来越明显。

同样的目的，也可以通过降低你的审美来达到——只要对错别字、中英混杂的标点等根本无感知，那么糟糕的样式对我来说有什么关系？

**Comment by jkvim** [comment]
yo, 是你翻译的呀 👍

**Comment by linesh-simplicity** [comment]
不是啊，我是打算翻一下。

**Comment by JimmyLv** [comment]
啊哈哈，欢迎加入 [影响力：将中文的好文章翻译成英文 · Issue #186 · JimmyLv/jimmylv.github.io](https://github.com/JimmyLv/jimmylv.github.io/issues/186)

**Comment by linesh-simplicity** [comment]
怎么加入哈哈哈

**Comment by JimmyLv** [comment]
要不我去建个 repo 😂

**Comment by JimmyLv** [comment]
要不我去建个 repo，2333

[[REFERENCE] · Issue #1 · JimmyLv/awesome-insights.zh2en](https://github.com/JimmyLv/awesome-insights.zh2en/issues/1)

**Comment by linesh-simplicity** [comment]
![image](https://user-images.githubusercontent.com/11895199/28529341-df1dae42-70c2-11e7-97f9-d42dbf297c3f.png)

233

**Comment by linesh-simplicity** [comment]
已无性趣，价值转化。暂时关闭，以观后效。
