### ISSUE TITLE
【博客2.0】个性化 - 他说

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#217]
我喜欢小众的情感和事物。这些东西往往没有办法通过正轨渠道表达出来，但有些小情小感，是否可以以轻量级的方式展示出来？比如一句话留言区。初步想法是，不占据主版面，又不难发现，作为彩蛋般的存在。每天固定只有一条，但不同天之间循环播放。

**Comment by JimmyLv** [comment]
哈哈，早有此想法，类似于微博的信息流之类的嘛，🤣

另外就是记录每天一些小的学习点，类似于 til（Today I Learn……）
