### ISSUE TITLE
To-think-list

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#66]
作为进一步需要被过滤的想法，已收纳到 Ticktick 的清单中去。同样的 issue 还有记录痛点的 #90

**Comment by JimmyLv** [comment]
强行链接过来安利，😂：https://github.com/JimmyLv/jimmylv.github.io/issues/88

**Comment by linesh-simplicity** [comment]
@JimmyLv 哈哈哈哈哈，你那个 issue 我还留过言的好嘛！真把 issue 当 QQ 空间使了是不！
