### ISSUE TITLE
公共 API 的学习

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#71]
- google map/hangouts/... api
- social media
- etc

**Comment by JimmyLv** [comment]
strongly recommend GitHub API

**Comment by linesh-simplicity** [comment]
A really interesting question is that, what can data be used for? What can we get out of from the data?

**Comment by JimmyLv** [comment]
@linesh-simplicity Just have fun with it which follow REST standards and have super excellent documentation.
