### ISSUE TITLE
元学习（二）：Learning How to Learn(Coursera)

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#99]
> **本篇所有的笔记会在 #121 进行二次整理。**

* http://www.brainfacts.org/
* recommended books: [clicks here](https://www.coursera.org/learn/learning-how-to-learn/resources/TJ084)

Course Resources
---

* Forums/Discussions: https://www.coursera.org/learn/learning-how-to-learn/discussions
* Resources: https://www.coursera.org/learn/learning-how-to-learn/resources/BbyV4
* Objectives: https://www.coursera.org/learn/learning-how-to-learn/resources/00u9I

Recommended reading on each chapter
---

* Chapter 1 further reading : https://www.coursera.org/learn/learning-how-to-learn/supplement/uWQyM/reading-focused-versus-diffuse-thinking
* Chapter 1 interviewing: https://www.coursera.org/learn/learning-how-to-learn/lecture/L4yKh/optional-interview-with-benny-the-irish-polyglot-about-learning-languages
* Chapter 2 further reading: https://www.coursera.org/learn/learning-how-to-learn/supplement/fWyi5/reading-chunking
* Chapter 2 interviewing: https://www.coursera.org/learn/learning-how-to-learn/lecture/NoDez/optional-interview-with-dr-norman-fortenberry-learning-at-mit
* Chapter 3 further reading : https://www.coursera.org/learn/learning-how-to-learn/supplement/H7Pv0/reading-procrastination-and-memory
* Chapter 3 interviewing: https://www.coursera.org/learn/learning-how-to-learn/lecture/hyLe9/optional-caroline-on-learning-something-difficult-that-others-think-isn-t-you
* Chapter 4 further reading: https://www.coursera.org/learn/learning-how-to-learn/supplement/bJW5V/reading-renaissance-learning-and-unlocking-your-potential
* Chapter 4 interviewing: https://www.coursera.org/learn/learning-how-to-learn/lecture/6093o/optional-part-1-how-not-to-take-a-test-interview-with-dr-richard-felder-and-dr

Course videos and books 
---

* https://www.coursera.org/learn/learning-how-to-learn
* [A Mind for Numbers](https://www.amazon.cn/gp/product/039916524X)

**Comment by linesh-simplicity** [comment]
## Two Modes of Thinking

two modes of learning, take the pinball game as an example.

* focused
* diffuse

**metaphor and analogy** helps when you trying to learn something new.

Some scientists found that **you can only be in one mode at a time**. In the focused mode, it helps you get deeper understanding of the subject, but we you trying to think around, there're always lots of bounces there blocking you from getting to another thinking pattern. Then **how do you get to know other patterns that you don't even know it exists before**? That's how diffuse mode helps.

> Question: I still don't understand how to get to know thinking patterns that you don't know(even its' existance) before.

**How do you use the two different modes?**

In order to learn things more effectively, your brain needs to **be able to switch back and forth** between the two different modes. 

> Question 1: Is diffuse mode efficient for more scientific courses?  
> Question 2: When are you feeling more relaxed/in a diffuse mode?  
> Question 3: How do you train your brain to switch back and forth between two different modes?

**Comment by linesh-simplicity** [comment]
# Chunking

* What is chunking? 
* How does it help when you are learning new things/subjects? 
* How to form a chunk? 
* How to know if a chunk is effective? 

## What is chunking?

**Comment by linesh-simplicity** [comment]
1. Procastination
---

## 

2. Memory
---

**Comment by JimmyLv** [comment]
牛掰啊！

**Comment by linesh-simplicity** [comment]
# How to become a better learner

**Comment by linesh-simplicity** [comment]
@JimmyLv 插楼删~

**Comment by linesh-simplicity** [comment]
![image](https://cloud.githubusercontent.com/assets/11895199/23557930/c0cbd9f8-006c-11e7-88ec-a34aa159fc6d.png)

可喜可贺。

**Comment by JimmyLv** [comment]
恭喜恭喜！

Linesh <notifications@github.com>于2017年3月3日周五 下午11:57写道：
